# Generated by Django 4.2.2 on 2023-06-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Ho', 'House'), ('C', 'Car'), ('Sp', 'Sports'), ('He', 'Health'), ('M', 'Market'), ('R', 'Restaurants'), ('D', 'Donations'), ('G', 'Gifts'), ('E', 'Entertainment'), ('O', 'Other')], default='Other', max_length=30),
        ),
    ]
