# Generated by Django 4.2.2 on 2023-06-27 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='recurring',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.card'),
        ),
    ]
