# Generated by Django 4.2.2 on 2023-06-30 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budget_recurring_alter_transaction_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Ho', 'House'), ('C', 'Car'), ('Sp', 'Sports'), ('He', 'Health'), ('M', 'Market'), ('R', 'Restaurants'), ('D', 'Donations'), ('Gl', 'Goal'), ('G', 'Gifts'), ('E', 'Entertainment'), ('O', 'Other')], default='Other', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('total_value', models.FloatField()),
                ('initial_value', models.FloatField()),
                ('desired_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.goal'),
        ),
    ]
